const express = require('express')
const route = express.Router()
const adminController = require('../controller/adminController')
const adminController_v2 = require('../controller/adminController_V2')
const {verifyTokenAdmin} = require('../middleware/veritify')
route.get('/household', verifyTokenAdmin, adminController.getHouseholdUsersInfo)
route.post('/household', verifyTokenAdmin, adminController.createHousehold)
route.post('/addUserToHousehold', verifyTokenAdmin, adminController.addUserToHousehold)
route.post('/addUser', verifyTokenAdmin, adminController.createUsers)
route.get('/user', verifyTokenAdmin, adminController.getAllUsersInHousehold)
route.post('/addFeeService', verifyTokenAdmin, adminController.addFeeService)
route.get('/feeService', verifyTokenAdmin, adminController.getFeeService)
route.post('/addHouseholdAndUser', verifyTokenAdmin, adminController.addHouseholdAndUser)
route.get('/getHouseholdUnactive', verifyTokenAdmin, adminController.getHouseholdUnactive)
route.get('/activeHousehold', verifyTokenAdmin, adminController.getHouseholdActive)
route.post('/addFeeUtility', verifyTokenAdmin, adminController.addFeeUtilityHouseholdPerMonth)
route.get('/getFeeUtility', verifyTokenAdmin, adminController.getFeeUtilityHouseholdPerMonth)
route.get('/householdInuse', verifyTokenAdmin, adminController.getHouseholdInuse)
route.post('/autoAdd', verifyTokenAdmin, adminController.autoAddManagementAndServiceFee)
route.get('/getAll', verifyTokenAdmin, adminController.getAllManagementAndServiceFees)
route.post('/addVehicle', verifyTokenAdmin, adminController_v2.addVehicle)
route.get('/getVehicle', verifyTokenAdmin, adminController_v2.getVehicle)
route.get('/allHouseholdPerMonth', verifyTokenAdmin, adminController.getHouseholdFeePerMonth)
route.put('/updatePayment', verifyTokenAdmin, adminController.updatePayment)
route.get('/fee-collection-data', verifyTokenAdmin, adminController.getFeeCollectionData)
route.get('/fee-type-distribution', verifyTokenAdmin, adminController.getFeeTypeDistribution)
route.get('/active-campaigns', verifyTokenAdmin, adminController.getActiveCampaigns)

route.post('/addContribution', verifyTokenAdmin, adminController.addContribution)
route.get('/getContribution', verifyTokenAdmin, adminController.getContribution)

route.get('/total-households', verifyTokenAdmin, adminController.getTotalHouseholds)
route.get('/unpaid-households', verifyTokenAdmin, adminController.getUnpaidHouseholds)
route.get('/unpaid-household-details', verifyTokenAdmin, adminController.getUnpaidHouseholdDetails)
route.get('/fee-summary', verifyTokenAdmin, adminController.getFeeSummary)
route.get('/user-residence/:userId', verifyTokenAdmin, adminController.getUserResidenceInfo)

module.exports = route