const express = require('express')
const route = express.Router()
const upload = require('../middleware/upload')
const adminController = require('../controller/adminController')
const adminController_v2 = require('../controller/adminController_V2')
const {verifyTokenAdmin, verifyTokenKetoan, verifyToken} = require('../middleware/veritify')
route.get('/household', verifyToken, adminController.getHouseholdUsersInfo)
route.post('/household', adminController.createHousehold)
route.post('/addUserToHousehold', verifyTokenAdmin, adminController.addUserToHousehold)
route.post('/addUser', verifyTokenAdmin, adminController.createUsers)
route.get('/user', verifyToken, adminController.getAllUsersInHousehold)
route.post('/addFeeService', verifyTokenAdmin, adminController.addFeeService)
route.get('/feeService', verifyToken, adminController.getFeeService)
route.post('/addHouseholdAndUser', verifyTokenAdmin, adminController.addHouseholdAndUser)
route.get('/getHouseholdUnactive',verifyToken, adminController.getHouseholdUnactive)
route.get('/activeHousehold', verifyToken, adminController.getHouseholdActive)
route.post('/addFeeUtility', verifyTokenKetoan, adminController.addFeeUtilityHouseholdPerMonth)
route.get('/getFeeUtility', verifyToken, adminController.getFeeUtilityHouseholdPerMonth)
route.get('/householdInuse', verifyToken, adminController.getHouseholdInuse)
route.post('/autoAdd', verifyTokenKetoan, adminController.autoAddManagementAndServiceFee)
route.get('/getAll', verifyToken, adminController.getAllManagementAndServiceFees)
route.post('/addVehicle', verifyTokenKetoan, adminController_v2.addVehicle)
route.get('/getVehicle', verifyToken, adminController_v2.getVehicle)
route.get('/allHouseholdPerMonth', verifyToken, adminController.getHouseholdFeePerMonth)
route.put('/updatePayment', verifyTokenKetoan, adminController.updatePayment)
route.get('/fee-collection-data', verifyToken, adminController.getFeeCollectionData)
route.get('/fee-type-distribution', verifyToken, adminController.getFeeTypeDistribution)
route.get('/active-campaigns', verifyToken, adminController.getActiveCampaigns)

route.post('/addContribution', verifyTokenKetoan, adminController.addContribution)
route.get('/getContribution', verifyToken, adminController.getContribution)

route.get('/total-households', verifyToken, adminController.getTotalHouseholds)
route.get('/unpaid-households', verifyToken, adminController.getUnpaidHouseholds)
route.get('/unpaid-household-details', verifyToken, adminController.getUnpaidHouseholdDetails)
route.get('/fee-summary', verifyToken, adminController.getFeeSummary)
route.get('/user-residence/:userId', verifyToken, adminController.getUserResidenceInfo)

route.post('/addContributionPayment', verifyTokenKetoan, adminController.addHouseholdToContribution)
route.get('/getContributionPayment', verifyToken, adminController.getContributionPayment)
route.get('/address', verifyToken, adminController.getAddressUser)
route.delete('/deleteHousehold', verifyTokenAdmin, adminController.deleteHousehold)
route.post('/import-fees', verifyTokenKetoan,upload.single('file'), adminController.importFeeFromExcel);


route.post('/reportUser', verifyToken, adminController.createReportUser)
route.get('/getReportUser', verifyToken, adminController.getReportUser)
route.put('/updateReportUser', verifyToken, adminController.updateReportUserResponse)
route.put('/updateReportUserStatusInProgress', verifyToken, adminController.updateReportUserStatusInProgress)
route.put('/updateReportUserStatusResolved', verifyToken, adminController.updateReportUserStatusResolved)
route.post('/addMemberToHousehold', verifyTokenAdmin, adminController.addMemberToHousehold)
route.delete('/delete', verifyTokenAdmin, adminController.deleteMember)
module.exports = route